Ext.define("test.store.list1store", {
extend:'Ext.data.Store',
requires:['test.model.list1model'],
config:{

  autoLoad:true,  
  sorters: 'firstName',
  id:'filterStore',
  grouper: {
            groupFn: function(record) {
                return record.get('firstName')[0];
            }},
data: [{
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'delhi',
                    city: 'city1',
                    lat: '28.66435',
                    long: '77.16546',
                    firstName: 'Tommy',
                    lastName: 'Maintz'
                }, {
                    pharmacy: 'y',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'delhi',
                    city: 'city1',
                    lat: '28.63214',
                    long: '77.13265',
                    firstName: 'Rob',
                    lastName: 'Dougan'
                }, {
                    pharmacy: 'y',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'delhi',
                    city: 'city2',
                    lat: '28.59568',
                    long: '77.26545',
                    firstName: 'Ed',
                    lastName: 'Avins'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'delhi',
                    city: 'city2',
                    lat: '28.60898',
                    long: '77.23654',
                    firstName: 'Jamie',
                    lastName: 'Avins'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'punjab',
                    city: 'city2',
                    lat: '28.65432',
                    long: '77.13564',
                    firstName: 'Dave',
                    lastName: 'Dougan'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'y',
                    state: 'punjab',
                    city: 'city2',
                    lat: '28.67156',
                    long: '77.19876',
                    firstName: 'Abraham',
                    lastName: 'Elias'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'y',
                    state: 'punjab',
                    city: 'city3',
                    lat: '28.63546',
                    long: '77.28165',
                    firstName: 'Jacky',
                    lastName: 'Ngyuyen'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'y',
                    state: 'punjab',
                    city: 'city3',
                    lat: '28.60654',
                    long: '77.23156',
                    firstName: 'Jay',
                    lastName: 'Ngyuyen'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'punjab',
                    city: 'city3',
                    lat: '28.65432',
                    long: '77.11465',
                    firstName: 'Jay',
                    lastName: 'Robinson'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'haryana',
                    city: 'city3',
                    lat: '28.59264',
                    long: '77.32465',
                    firstName: 'Rob',
                    lastName: 'Avins'
                }, {
                    pharmacy: 'n',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'haryana',
                    city: 'city4',
                    lat: '28.61659',
                    long: '77.10926',
                    firstName: 'Ed',
                    lastName: 'Dougan'
                }, {
                    pharmacy: 'n',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'haryana',
                    city: 'city4',
                    lat: '28.63259',
                    long: '77.16876',
                    firstName: 'Jamie',
                    lastName: 'Poulden'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'haryana',
                    city: 'city4',
                    lat: '28.66265',
                    long: '77.19872',
                    firstName: 'Dave',
                    lastName: 'Spencer'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'Uttar Pradesh',
                    city: 'city5',
                    lat: '28.64356',
                    long: '77.16987',
                    firstName: 'Abraham',
                    lastName: 'Avins'
                }, {
                    pharmacy: 'y',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'Uttar Pradesh',
                    city: 'city5',
                    lat: '28.65423',
                    long: '77.17564',
                    firstName: 'Jacky',
                    lastName: 'Avins'
                }, {
                    pharmacy: 'n',
                    ambulance: 'y',
                    gov: 'n',
                    state: 'Himachal Pradesh',
                    city: 'city6',
                    lat: '28.65987',
                    long: '77.26546',
                    firstName: 'Rob',
                    lastName: 'Kaneda'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'n',
                    state: 'Himachal Pradesh',
                    city: 'city6',
                    lat: '28.60598',
                    long: '77.21035',
                    firstName: 'Ed',
                    lastName: 'Elias'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'n',
                    state: 'Himachal Pradesh',
                    city: 'city7',
                    lat: '28.65432',
                    long: '77.23246',
                    firstName: 'Tommy',
                    lastName: 'Dougan'
                }, {
                    pharmacy: 'n',
                    ambulance: 'n',
                    gov: 'n',
                    state: 'Himachal Pradesh',
                    city: 'city7',
                    lat: '28.65432',
                    long: '77.10654',
                    firstName: 'Rob',
                    lastName: 'Robinson'
                }]
}
});